### PR TITLE
parse returns a lazy seq of vectors, delimiter support, parsing strings.

### PR DESCRIPTION
**Pull request by RobinRamael**
Hi,

I added the possibility to let parse return a lazy-seq of vectors instead of maps,
added basic support for using custom delimiters and support for parsing strings instead of just reading from files.
I hope this project isn't dead, it's the only parser that worked for me...
(disregard the ither pull requet I closed, there were problems with it)

Robin

### CODE REVIEW

**Comment by grinnbearit** [comment]
Not at all, I just haven't seen this code for a while

Do you feel that instead of adding multiple readers, i.e. for files, strings, urls etc it could be made more general? Just accepting reader for instance.

Also the vectors is a good idea, how bout trying optional keyword params instead of arguments. That way it could be changed later to allow more options without breaking existing code.

**Comment by RobinRamael** [comment]
You're right, just accepting a reader and arguments would be best.
I see the usage then being something like `(csv/parse reader :mapped (true/false) :delimiter \; :end-of-line \\r)`.

I probably pushed this too soon, as i'm still figuring out what I need the parser to do myself. I'll push my work to this request when I'm sure.

**Comment by grinnbearit** [comment]
sounds good,
(defn parse [reader & {:keys [mapped delimiter end-of-line] :or {mapped
false delimiter \, end-of-line \r}]
   ...)

**Comment by RobinRamael** [comment]
There we go. I've implemented the parse function with the options, added the parse-file and parse-string helper-functions, added tests and updated the readme.

**Comment by grinnbearit** [comment]
looks great! merged

**Pull request merged**
